# Generated by Django 4.2 on 2023-04-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0003_alter_correo_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejecutivo',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
