# Generated by Django 4.1.8 on 2023-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0005_alter_correo_ejecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='ejecutivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
