# Generated by Django 4.1.8 on 2023-05-18 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correos', '0006_alter_correo_ejecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
